### ISSUE TITLE
[doc] Please provide agent as container

### ISSUE THREAD

**Issue by kaka2991** [Kraken-CI/kraken#100]
This: https://kraken.ci/docs/agents#setting-up-a-new-agent is not going to work on macOS. Can you provide in the doc alternative way of running agent, for example as docker container? Besides I'm using macOS, but please note that not everyone would like to install on his OS kraken agent to only test the tool. You are already providing quick and safe method to run test kraken instance (.env and compose file). Why not add here agent? It can be simply docker run with -e argument with kraken URL.

**Comment by godfryd** [comment]
There is already present agent in compose. You need to authorize it on Agents page.

Beside that it make sense to describe setting up an agent in a container.

**Comment by kaka2991** [comment]
> There is already present agent in compose. You need to authorize it on Agents page.
"Server" as agent name may be ambiguous.

**Comment by godfryd** [comment]
Added more details about setting up a new agent, including starting it via Docker.

It can be found here: https://kraken.ci/docs/agents
