### ISSUE TITLE
Close child container when agent is shutting down

### ISSUE THREAD

**Issue by ppieczul** [Kraken-CI/kraken#19]
Agent should close container executing jobs when it is shutting down. Otherwise this container is left and it prevents lab network from shutting down too.

**Comment by godfryd** [comment]
Currently there is a stop function that is called at the end of a job and it does:
```python
    def stop(self):
        try:
            self.cntr.kill()
        except:
            log.exception('IGNORED EXCEPTION')
        try:
            self.cntr.remove()
        except:
            log.exception('IGNORED EXCEPTION')
```

**Comment by godfryd** [comment]
it should be fixed - please check
