### ISSUE TITLE
Docker-compose method warns that env variables aren't set.

### ISSUE THREAD

**Issue by johnl800** [Kraken-CI/kraken#205]
Set-up: WSL2 with Ubuntu 22.04.  Docker utils are supplied to Ubuntu from Docker Desktop for Windows.

johnl@DESKTOP-FDQ7CV5:~$ sudo docker-compose -f kraken-docker-compose-0.962.yaml ps
WARN[0000] The "KRAKEN_MINIO_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_MINIO_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_MINIO_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_MINIO_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_UI_PUBLIC_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_SERVER_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_SERVER_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_SERVER_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_CLICKHOUSE_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_CLICKHOUSE_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "KRAKEN_CLICKHOUSE_PORT" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

* error decoding 'Ports': No port specified: :<empty>
johnl@DESKTOP-FDQ7CV5:~$

I was able to login to the Kraken GUI, which indicates that the port configuration matches the environment file.

I noticed that the the warnings correspond to the $<variable> entries in the .yaml file.  I'm a little surprised that this didn't either: work without any warning or fail to import the values from the environment file.

Also, "sudo docker-compose -f kraken-docker-compose-0.962.yaml down" didn't work. I stopped it in the Docker GUI instead.

**Comment by godfryd** [comment]
Hello,

Try not to use sudo - I think that this is not needed.

How did you run docker-compose up?
Did you pass --env-file parameter?
Check the second step at https://kraken.ci/docs/quick-start

Regards,
Michał Nowikowski
