### ISSUE TITLE
Unable to login using Google IdentityProvider

### ISSUE THREAD

**Issue by roboptics** [Kraken-CI/kraken#274]
Using version 1.1.45 and configuring Google Identity Provider. 
The login flow completes sucessfully, but the following errors show after redirecting from google to the application. In the end we are back to the login screen.

![image](https://github.com/Kraken-CI/kraken/assets/17877466/87aafecb-b396-44e1-b70c-76a841778df1)

Let me know which additional information I can send to help diagnose.

**Comment by godfryd** [comment]
Hello,
Some basic questions upfront.
Did you follow the instructions from:
https://kraken.ci/docs/users#identity-providers
Did you fill Client ID and Client Secret in Google section?
Could you sent logs from Kraken Server?
Could you check if there are any errors in the console in your web browser 
(as on your screenshot, switch from network tab to console tab)?

**Comment by godfryd** [comment]
Hmm, I'm reproducing the problem on my side.
Please, wait for a fix.

**Comment by godfryd** [comment]
Please, check 1.2 release: https://github.com/Kraken-CI/kraken/releases/tag/v1.2
I fixed some issue in user session handling.
If it does not help, then please check console log in web browser.

**Comment by roboptics** [comment]
Seems to be working!
Thank you for your quick support :)
