### ISSUE TITLE
git tool cannot clone with URLs like https://seed.radicle.xyz/z3gqcJUoA1n9HaHKufZs5FCSGazv5.git 

### ISSUE THREAD

**Issue by gsaslis** [Kraken-CI/kraken#277]
This actually seems to be an issue with the underlying giturlparse library (I have opened an [issue](https://github.com/nephila/giturlparse/issues/59) in their repo), but I thought I'd also mention here.

**Comment by michaln-gc** [comment]
Ok, I see it. They have a fix but didn't make a release yet.
I will try to update requirements.txt and pull the package directly using SHA
and later I will update it again when the official release is provided.

**Comment by godfryd** [comment]
Ok, I see it. They have a fix but didn't make a release yet.
I will try to update requirements.txt and pull the package directly using SHA
and later I will update it again when the official release is provided.

**Comment by gsaslis** [comment]
👏🏼 thanks so much for taking care of this @godfryd ! 👍🏼

**Comment by godfryd** [comment]
It will be released in a week or two.

wt., 4 lip 2023, 09:29 użytkownik Yorgos Saslis ***@***.***>
napisał:

**Comment by gsaslis** [comment]
Hey @godfryd ! 👋🏼 

just a heads up that the [underlying issue](https://github.com/nephila/giturlparse/issues/59) has been included in the latest `giturlparse` release ;)
